all: test_multiset prime_factors
test_multiset:
	g++ -Wall -Werror -std=c++11 -o test_multiset test_multiset.cc
prime_factors:
	g++ -Wall -Werror -std=c++11 -o prime_factors prime_factors.cc
clean:
	rm -f prime_factors
	rm -f test_multiset
